# Generated by Django 4.0.5 on 2022-07-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_authors_alter_books_released_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='released_year',
            field=models.IntegerField(),
        ),
    ]
