# Generated by Django 4.0.5 on 2022-07-07 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0003_alter_books_released_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
