# Generated by Django 4.0.5 on 2022-07-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0009_review_create_at_review_update_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
